// src/lib/stockList.ts

export interface StockSymbol {
  symbol: string;
  name: string;
  sector?: string;
}

// TODO: User to paste full Nifty 500 + F&O list here
export const STOCK_LIST: StockSymbol[] = [
  { symbol: '360ONE.NS', name: "360 ONE WAM Ltd.", sector: 'Financial Services' },
  { symbol: '3MINDIA.NS', name: "3M India Ltd.", sector: 'Diversified' },
  { symbol: 'ABB.NS', name: "ABB India Ltd.", sector: 'Capital Goods' },
  { symbol: 'ACC.NS', name: "ACC Ltd.", sector: 'Construction Materials' },
  { symbol: 'ACMESOLAR.NS', name: "ACME Solar Holdings Ltd.", sector: 'Power' },
  { symbol: 'AIAENG.NS', name: "AIA Engineering Ltd.", sector: 'Capital Goods' },
  { symbol: 'APLAPOLLO.NS', name: "APL Apollo Tubes Ltd.", sector: 'Capital Goods' },
  { symbol: 'AUBANK.NS', name: "AU Small Finance Bank Ltd.", sector: 'Financial Services' },
  { symbol: 'AWL.NS', name: "AWL Agri Business Ltd.", sector: 'Fast Moving Consumer Goods' },
  { symbol: 'AADHARHFC.NS', name: "Aadhar Housing Finance Ltd.", sector: 'Financial Services' },
  { symbol: 'AARTIIND.NS', name: "Aarti Industries Ltd.", sector: 'Chemicals' },
  { symbol: 'AAVAS.NS', name: "Aavas Financiers Ltd.", sector: 'Financial Services' },
  { symbol: 'ABBOTINDIA.NS', name: "Abbott India Ltd.", sector: 'Healthcare' },
  { symbol: 'ACE.NS', name: "Action Construction Equipment Ltd.", sector: 'Capital Goods' },
  { symbol: 'ADANIENSOL.NS', name: "Adani Energy Solutions Ltd.", sector: 'Power' },
  { symbol: 'ADANIENT.NS', name: "Adani Enterprises Ltd.", sector: 'Metals & Mining' },
  { symbol: 'ADANIGREEN.NS', name: "Adani Green Energy Ltd.", sector: 'Power' },
  { symbol: 'ADANIPORTS.NS', name: "Adani Ports and Special Economic Zone Ltd.", sector: 'Services' },
  { symbol: 'ADANIPOWER.NS', name: "Adani Power Ltd.", sector: 'Power' },
  { symbol: 'ATGL.NS', name: "Adani Total Gas Ltd.", sector: 'Oil Gas & Consumable Fuels' },
  { symbol: 'ABCAPITAL.NS', name: "Aditya Birla Capital Ltd.", sector: 'Financial Services' },
  { symbol: 'ABFRL.NS', name: "Aditya Birla Fashion and Retail Ltd.", sector: 'Consumer Services' },
  { symbol: 'ABLBL.NS', name: "Aditya Birla Lifestyle Brands Ltd.", sector: 'Consumer Services' },
  { symbol: 'ABREL.NS', name: "Aditya Birla Real Estate Ltd.", sector: 'Forest Materials' },
  { symbol: 'ABSLAMC.NS', name: "Aditya Birla Sun Life AMC Ltd.", sector: 'Financial Services' },
  { symbol: 'AEGISLOG.NS', name: "Aegis Logistics Ltd.", sector: 'Oil Gas & Consumable Fuels' },
  { symbol: 'AEGISVOPAK.NS', name: "Aegis Vopak Terminals Ltd.", sector: 'Oil Gas & Consumable Fuels' },
  { symbol: 'AFCONS.NS', name: "Afcons Infrastructure Ltd.", sector: 'Construction' },
  { symbol: 'AFFLE.NS', name: "Affle 3i Ltd.", sector: 'Information Technology' },
  { symbol: 'AJANTPHARM.NS', name: "Ajanta Pharmaceuticals Ltd.", sector: 'Healthcare' },
  { symbol: 'AKUMS.NS', name: "Akums Drugs and Pharmaceuticals Ltd.", sector: 'Healthcare' },
  { symbol: 'AKZOINDIA.NS', name: "Akzo Nobel India Ltd.", sector: 'Consumer Durables' },
  { symbol: 'APLLTD.NS', name: "Alembic Pharmaceuticals Ltd.", sector: 'Healthcare' },
  { symbol: 'ALKEM.NS', name: "Alkem Laboratories Ltd.", sector: 'Healthcare' },
  { symbol: 'ALKYLAMINE.NS', name: "Alkyl Amines Chemicals Ltd.", sector: 'Chemicals' },
  { symbol: 'ALOKINDS.NS', name: "Alok Industries Ltd.", sector: 'Textiles' },
  { symbol: 'ARE&M.NS', name: "Amara Raja Energy & Mobility Ltd.", sector: 'Automobile and Auto Components' },
  { symbol: 'AMBER.NS', name: "Amber Enterprises India Ltd.", sector: 'Consumer Durables' },
  { symbol: 'AMBUJACEM.NS', name: "Ambuja Cements Ltd.", sector: 'Construction Materials' },
  { symbol: 'ANANDRATHI.NS', name: "Anand Rathi Wealth Ltd.", sector: 'Financial Services' },
  { symbol: 'ANANTRAJ.NS', name: "Anant Raj Ltd.", sector: 'Realty' },
  { symbol: 'ANGELONE.NS', name: "Angel One Ltd.", sector: 'Financial Services' },
  { symbol: 'APARINDS.NS', name: "Apar Industries Ltd.", sector: 'Capital Goods' },
  { symbol: 'APOLLOHOSP.NS', name: "Apollo Hospitals Enterprise Ltd.", sector: 'Healthcare' },
  { symbol: 'APOLLOTYRE.NS', name: "Apollo Tyres Ltd.", sector: 'Automobile and Auto Components' },
  { symbol: 'APTUS.NS', name: "Aptus Value Housing Finance India Ltd.", sector: 'Financial Services' },
  { symbol: 'ASAHIINDIA.NS', name: "Asahi India Glass Ltd.", sector: 'Automobile and Auto Components' },
  { symbol: 'ASHOKLEY.NS', name: "Ashok Leyland Ltd.", sector: 'Capital Goods' },
  { symbol: 'ASIANPAINT.NS', name: "Asian Paints Ltd.", sector: 'Consumer Durables' },
  { symbol: 'ASTERDM.NS', name: "Aster DM Healthcare Ltd.", sector: 'Healthcare' },
  { symbol: 'ASTRAZEN.NS', name: "AstraZenca Pharma India Ltd.", sector: 'Healthcare' },
  { symbol: 'ASTRAL.NS', name: "Astral Ltd.", sector: 'Capital Goods' },
  { symbol: 'ATHERENERG.NS', name: "Ather Energy Ltd.", sector: 'Automobile and Auto Components' },
  { symbol: 'ATUL.NS', name: "Atul Ltd.", sector: 'Chemicals' },
  { symbol: 'AUROPHARMA.NS', name: "Aurobindo Pharma Ltd.", sector: 'Healthcare' },
  { symbol: 'AIIL.NS', name: "Authum Investment & Infrastructure Ltd.", sector: 'Financial Services' },
  { symbol: 'DMART.NS', name: "Avenue Supermarts Ltd.", sector: 'Consumer Services' },
  { symbol: 'AXISBANK.NS', name: "Axis Bank Ltd.", sector: 'Financial Services' },
  { symbol: 'BASF.NS', name: "BASF India Ltd.", sector: 'Chemicals' },
  { symbol: 'BEML.NS', name: "BEML Ltd.", sector: 'Capital Goods' },
  { symbol: 'BLS.NS', name: "BLS International Services Ltd.", sector: 'Consumer Services' },
  { symbol: 'BSE.NS', name: "BSE Ltd.", sector: 'Financial Services' },
  { symbol: 'BAJAJ-AUTO.NS', name: "Bajaj Auto Ltd.", sector: 'Automobile and Auto Components' },
  { symbol: 'BAJFINANCE.NS', name: "Bajaj Finance Ltd.", sector: 'Financial Services' },
  { symbol: 'BAJAJFINSV.NS', name: "Bajaj Finserv Ltd.", sector: 'Financial Services' },
  { symbol: 'BAJAJHLDNG.NS', name: "Bajaj Holdings & Investment Ltd.", sector: 'Financial Services' },
  { symbol: 'BAJAJHFL.NS', name: "Bajaj Housing Finance Ltd.", sector: 'Financial Services' },
  { symbol: 'BALKRISIND.NS', name: "Balkrishna Industries Ltd.", sector: 'Automobile and Auto Components' },
  { symbol: 'BALRAMCHIN.NS', name: "Balrampur Chini Mills Ltd.", sector: 'Fast Moving Consumer Goods' },
  { symbol: 'BANDHANBNK.NS', name: "Bandhan Bank Ltd.", sector: 'Financial Services' },
  { symbol: 'BANKBARODA.NS', name: "Bank of Baroda", sector: 'Financial Services' },
  { symbol: 'BANKINDIA.NS', name: "Bank of India", sector: 'Financial Services' },
  { symbol: 'MAHABANK.NS', name: "Bank of Maharashtra", sector: 'Financial Services' },
  { symbol: 'BATAINDIA.NS', name: "Bata India Ltd.", sector: 'Consumer Durables' },
  { symbol: 'BAYERCROP.NS', name: "Bayer Cropscience Ltd.", sector: 'Chemicals' },
  { symbol: 'BERGEPAINT.NS', name: "Berger Paints India Ltd.", sector: 'Consumer Durables' },
  { symbol: 'BDL.NS', name: "Bharat Dynamics Ltd.", sector: 'Capital Goods' },
  { symbol: 'BEL.NS', name: "Bharat Electronics Ltd.", sector: 'Capital Goods' },
  { symbol: 'BHARATFORG.NS', name: "Bharat Forge Ltd.", sector: 'Automobile and Auto Components' },
  { symbol: 'BHEL.NS', name: "Bharat Heavy Electricals Ltd.", sector: 'Capital Goods' },
  { symbol: 'BPCL.NS', name: "Bharat Petroleum Corporation Ltd.", sector: 'Oil Gas & Consumable Fuels' },
  { symbol: 'BHARTIARTL.NS', name: "Bharti Airtel Ltd.", sector: 'Telecommunication' },
  { symbol: 'BHARTIHEXA.NS', name: "Bharti Hexacom Ltd.", sector: 'Telecommunication' },
  { symbol: 'BIKAJI.NS', name: "Bikaji Foods International Ltd.", sector: 'Fast Moving Consumer Goods' },
  { symbol: 'BIOCON.NS', name: "Biocon Ltd.", sector: 'Healthcare' },
  { symbol: 'BSOFT.NS', name: "Birlasoft Ltd.", sector: 'Information Technology' },
  { symbol: 'BLUEDART.NS', name: "Blue Dart Express Ltd.", sector: 'Services' },
  { symbol: 'BLUEJET.NS', name: "Blue Jet Healthcare Ltd.", sector: 'Healthcare' },
  { symbol: 'BLUESTARCO.NS', name: "Blue Star Ltd.", sector: 'Consumer Durables' },
  { symbol: 'BBTC.NS', name: "Bombay Burmah Trading Corporation Ltd.", sector: 'Fast Moving Consumer Goods' },
  { symbol: 'BOSCHLTD.NS', name: "Bosch Ltd.", sector: 'Automobile and Auto Components' },
  { symbol: 'FIRSTCRY.NS', name: "Brainbees Solutions Ltd.", sector: 'Consumer Services' },
  { symbol: 'BRIGADE.NS', name: "Brigade Enterprises Ltd.", sector: 'Realty' },
  { symbol: 'BRITANNIA.NS', name: "Britannia Industries Ltd.", sector: 'Fast Moving Consumer Goods' },
  { symbol: 'MAPMYINDIA.NS', name: "C.E. Info Systems Ltd.", sector: 'Information Technology' },
  { symbol: 'CCL.NS', name: "CCL Products (I) Ltd.", sector: 'Fast Moving Consumer Goods' },
  { symbol: 'CESC.NS', name: "CESC Ltd.", sector: 'Power' },
  { symbol: 'CGPOWER.NS', name: "CG Power and Industrial Solutions Ltd.", sector: 'Capital Goods' },
  { symbol: 'CRISIL.NS', name: "CRISIL Ltd.", sector: 'Financial Services' },
  { symbol: 'CAMPUS.NS', name: "Campus Activewear Ltd.", sector: 'Consumer Durables' },
  { symbol: 'CANFINHOME.NS', name: "Can Fin Homes Ltd.", sector: 'Financial Services' },
  { symbol: 'CANBK.NS', name: "Canara Bank", sector: 'Financial Services' },
  { symbol: 'CAPLIPOINT.NS', name: "Caplin Point Laboratories Ltd.", sector: 'Healthcare' },
  { symbol: 'CGCL.NS', name: "Capri Global Capital Ltd.", sector: 'Financial Services' },
  { symbol: 'CARBORUNIV.NS', name: "Carborundum Universal Ltd.", sector: 'Capital Goods' },
  { symbol: 'CASTROLIND.NS', name: "Castrol India Ltd.", sector: 'Oil Gas & Consumable Fuels' },
  { symbol: 'CEATLTD.NS', name: "Ceat Ltd.", sector: 'Automobile and Auto Components' },
  { symbol: 'CENTRALBK.NS', name: "Central Bank of India", sector: 'Financial Services' },
  { symbol: 'CDSL.NS', name: "Central Depository Services (India) Ltd.", sector: 'Financial Services' },
  { symbol: 'CENTURYPLY.NS', name: "Century Plyboards (India) Ltd.", sector: 'Consumer Durables' },
  { symbol: 'CERA.NS', name: "Cera Sanitaryware Ltd", sector: 'Consumer Durables' },
  { symbol: 'CHALET.NS', name: "Chalet Hotels Ltd.", sector: 'Consumer Services' },
  { symbol: 'CHAMBLFERT.NS', name: "Chambal Fertilizers & Chemicals Ltd.", sector: 'Chemicals' },
  { symbol: 'CHENNPETRO.NS', name: "Chennai Petroleum Corporation Ltd.", sector: 'Oil Gas & Consumable Fuels' },
  { symbol: 'CHOICEIN.NS', name: "Choice International Ltd.", sector: 'Financial Services' },
  { symbol: 'CHOLAHLDNG.NS', name: "Cholamandalam Financial Holdings Ltd.", sector: 'Financial Services' },
  { symbol: 'CHOLAFIN.NS', name: "Cholamandalam Investment and Finance Company Ltd.", sector: 'Financial Services' },
  { symbol: 'CIPLA.NS', name: "Cipla Ltd.", sector: 'Healthcare' },
  { symbol: 'CUB.NS', name: "City Union Bank Ltd.", sector: 'Financial Services' },
  { symbol: 'CLEAN.NS', name: "Clean Science and Technology Ltd.", sector: 'Chemicals' },
  { symbol: 'COALINDIA.NS', name: "Coal India Ltd.", sector: 'Oil Gas & Consumable Fuels' },
  { symbol: 'COCHINSHIP.NS', name: "Cochin Shipyard Ltd.", sector: 'Capital Goods' },
  { symbol: 'COFORGE.NS', name: "Coforge Ltd.", sector: 'Information Technology' },
  { symbol: 'COHANCE.NS', name: "Cohance Lifesciences Ltd.", sector: 'Healthcare' },
  { symbol: 'COLPAL.NS', name: "Colgate Palmolive (India) Ltd.", sector: 'Fast Moving Consumer Goods' },
  { symbol: 'CAMS.NS', name: "Computer Age Management Services Ltd.", sector: 'Financial Services' },
  { symbol: 'CONCORDBIO.NS', name: "Concord Biotech Ltd.", sector: 'Healthcare' },
  { symbol: 'CONCOR.NS', name: "Container Corporation of India Ltd.", sector: 'Services' },
  { symbol: 'COROMANDEL.NS', name: "Coromandel International Ltd.", sector: 'Chemicals' },
  { symbol: 'CRAFTSMAN.NS', name: "Craftsman Automation Ltd.", sector: 'Automobile and Auto Components' },
  { symbol: 'CREDITACC.NS', name: "CreditAccess Grameen Ltd.", sector: 'Financial Services' },
  { symbol: 'CROMPTON.NS', name: "Crompton Greaves Consumer Electricals Ltd.", sector: 'Consumer Durables' },
  { symbol: 'CUMMINSIND.NS', name: "Cummins India Ltd.", sector: 'Capital Goods' },
  { symbol: 'CYIENT.NS', name: "Cyient Ltd.", sector: 'Information Technology' },
  { symbol: 'DCMSHRIRAM.NS', name: "DCM Shriram Ltd.", sector: 'Diversified' },
  { symbol: 'DLF.NS', name: "DLF Ltd.", sector: 'Realty' },
  { symbol: 'DOMS.NS', name: "DOMS Industries Ltd.", sector: 'Fast Moving Consumer Goods' },
  { symbol: 'DABUR.NS', name: "Dabur India Ltd.", sector: 'Fast Moving Consumer Goods' },
  { symbol: 'DALBHARAT.NS', name: "Dalmia Bharat Ltd.", sector: 'Construction Materials' },
  { symbol: 'DATAPATTNS.NS', name: "Data Patterns (India) Ltd.", sector: 'Capital Goods' },
  { symbol: 'DEEPAKFERT.NS', name: "Deepak Fertilisers & Petrochemicals Corp. Ltd.", sector: 'Chemicals' },
  { symbol: 'DEEPAKNTR.NS', name: "Deepak Nitrite Ltd.", sector: 'Chemicals' },
  { symbol: 'DELHIVERY.NS', name: "Delhivery Ltd.", sector: 'Services' },
  { symbol: 'DEVYANI.NS', name: "Devyani International Ltd.", sector: 'Consumer Services' },
  { symbol: 'DIVISLAB.NS', name: "Divi's Laboratories Ltd.", sector: 'Healthcare' },
  { symbol: 'DIXON.NS', name: "Dixon Technologies (India) Ltd.", sector: 'Consumer Durables' },
  { symbol: 'AGARWALEYE.NS', name: "Dr. Agarwal's Health Care Ltd.", sector: 'Healthcare' },
  { symbol: 'LALPATHLAB.NS', name: "Dr. Lal Path Labs Ltd.", sector: 'Healthcare' },
  { symbol: 'DRREDDY.NS', name: "Dr. Reddy's Laboratories Ltd.", sector: 'Healthcare' },
  { symbol: 'DUMMYHDLVR.NS', name: "Dummy Hindustan Unilever Ltd.", sector: 'Fast Moving Consumer Goods' },
  { symbol: 'EIDPARRY.NS', name: "E.I.D. Parry (India) Ltd.", sector: 'Fast Moving Consumer Goods' },
  { symbol: 'EIHOTEL.NS', name: "EIH Ltd.", sector: 'Consumer Services' },
  { symbol: 'EICHERMOT.NS', name: "Eicher Motors Ltd.", sector: 'Automobile and Auto Components' },
  { symbol: 'ELECON.NS', name: "Elecon Engineering Co. Ltd.", sector: 'Capital Goods' },
  { symbol: 'ELGIEQUIP.NS', name: "Elgi Equipments Ltd.", sector: 'Capital Goods' },
  { symbol: 'EMAMILTD.NS', name: "Emami Ltd.", sector: 'Fast Moving Consumer Goods' },
  { symbol: 'EMCURE.NS', name: "Emcure Pharmaceuticals Ltd.", sector: 'Healthcare' },
  { symbol: 'ENDURANCE.NS', name: "Endurance Technologies Ltd.", sector: 'Automobile and Auto Components' },
  { symbol: 'ENGINERSIN.NS', name: "Engineers India Ltd.", sector: 'Construction' },
  { symbol: 'ERIS.NS', name: "Eris Lifesciences Ltd.", sector: 'Healthcare' },
  { symbol: 'ESCORTS.NS', name: "Escorts Kubota Ltd.", sector: 'Capital Goods' },
  { symbol: 'ETERNAL.NS', name: "Eternal Ltd.", sector: 'Consumer Services' },
  { symbol: 'EXIDEIND.NS', name: "Exide Industries Ltd.", sector: 'Automobile and Auto Components' },
  { symbol: 'NYKAA.NS', name: "FSN E-Commerce Ventures Ltd.", sector: 'Consumer Services' },
  { symbol: 'FEDERALBNK.NS', name: "Federal Bank Ltd.", sector: 'Financial Services' },
  { symbol: 'FACT.NS', name: "Fertilisers and Chemicals Travancore Ltd.", sector: 'Chemicals' },
  { symbol: 'FINCABLES.NS', name: "Finolex Cables Ltd.", sector: 'Capital Goods' },
  { symbol: 'FINPIPE.NS', name: "Finolex Industries Ltd.", sector: 'Capital Goods' },
  { symbol: 'FSL.NS', name: "Firstsource Solutions Ltd.", sector: 'Services' },
  { symbol: 'FIVESTAR.NS', name: "Five-Star Business Finance Ltd.", sector: 'Financial Services' },
  { symbol: 'FORCEMOT.NS', name: "Force Motors Ltd.", sector: 'Automobile and Auto Components' },
  { symbol: 'FORTIS.NS', name: "Fortis Healthcare Ltd.", sector: 'Healthcare' },
  { symbol: 'GAIL.NS', name: "GAIL (India) Ltd.", sector: 'Oil Gas & Consumable Fuels' },
  { symbol: 'GVT&D.NS', name: "GE Vernova T&D India Ltd.", sector: 'Capital Goods' },
  { symbol: 'GMRAIRPORT.NS', name: "GMR Airports Ltd.", sector: 'Services' },
  { symbol: 'GRSE.NS', name: "Garden Reach Shipbuilders & Engineers Ltd.", sector: 'Capital Goods' },
  { symbol: 'GICRE.NS', name: "General Insurance Corporation of India", sector: 'Financial Services' },
  { symbol: 'GILLETTE.NS', name: "Gillette India Ltd.", sector: 'Fast Moving Consumer Goods' },
  { symbol: 'GLAND.NS', name: "Gland Pharma Ltd.", sector: 'Healthcare' },
  { symbol: 'GLAXO.NS', name: "Glaxosmithkline Pharmaceuticals Ltd.", sector: 'Healthcare' },
  { symbol: 'GLENMARK.NS', name: "Glenmark Pharmaceuticals Ltd.", sector: 'Healthcare' },
  { symbol: 'MEDANTA.NS', name: "Global Health Ltd.", sector: 'Healthcare' },
  { symbol: 'GODIGIT.NS', name: "Go Digit General Insurance Ltd.", sector: 'Financial Services' },
  { symbol: 'GPIL.NS', name: "Godawari Power & Ispat Ltd.", sector: 'Capital Goods' },
  { symbol: 'GODFRYPHLP.NS', name: "Godfrey Phillips India Ltd.", sector: 'Fast Moving Consumer Goods' },
  { symbol: 'GODREJAGRO.NS', name: "Godrej Agrovet Ltd.", sector: 'Fast Moving Consumer Goods' },
  { symbol: 'GODREJCP.NS', name: "Godrej Consumer Products Ltd.", sector: 'Fast Moving Consumer Goods' },
  { symbol: 'GODREJIND.NS', name: "Godrej Industries Ltd.", sector: 'Diversified' },
  { symbol: 'GODREJPROP.NS', name: "Godrej Properties Ltd.", sector: 'Realty' },
  { symbol: 'GRANULES.NS', name: "Granules India Ltd.", sector: 'Healthcare' },
  { symbol: 'GRAPHITE.NS', name: "Graphite India Ltd.", sector: 'Capital Goods' },
  { symbol: 'GRASIM.NS', name: "Grasim Industries Ltd.", sector: 'Construction Materials' },
  { symbol: 'GRAVITA.NS', name: "Gravita India Ltd.", sector: 'Metals & Mining' },
  { symbol: 'GESHIP.NS', name: "Great Eastern Shipping Co. Ltd.", sector: 'Services' },
  { symbol: 'FLUOROCHEM.NS', name: "Gujarat Fluorochemicals Ltd.", sector: 'Chemicals' },
  { symbol: 'GUJGASLTD.NS', name: "Gujarat Gas Ltd.", sector: 'Oil Gas & Consumable Fuels' },
  { symbol: 'GMDCLTD.NS', name: "Gujarat Mineral Development Corporation Ltd.", sector: 'Metals & Mining' },
  { symbol: 'GSPL.NS', name: "Gujarat State Petronet Ltd.", sector: 'Oil Gas & Consumable Fuels' },
  { symbol: 'HEG.NS', name: "H.E.G. Ltd.", sector: 'Capital Goods' },
  { symbol: 'HBLENGINE.NS', name: "HBL Engineering Ltd.", sector: 'Capital Goods' },
  { symbol: 'HCLTECH.NS', name: "HCL Technologies Ltd.", sector: 'Information Technology' },
  { symbol: 'HDFCAMC.NS', name: "HDFC Asset Management Company Ltd.", sector: 'Financial Services' },
  { symbol: 'HDFCBANK.NS', name: "HDFC Bank Ltd.", sector: 'Financial Services' },
  { symbol: 'HDFCLIFE.NS', name: "HDFC Life Insurance Company Ltd.", sector: 'Financial Services' },
  { symbol: 'HFCL.NS', name: "HFCL Ltd.", sector: 'Telecommunication' },
  { symbol: 'HAPPSTMNDS.NS', name: "Happiest Minds Technologies Ltd.", sector: 'Information Technology' },
  { symbol: 'HAVELLS.NS', name: "Havells India Ltd.", sector: 'Consumer Durables' },
  { symbol: 'HEROMOTOCO.NS', name: "Hero MotoCorp Ltd.", sector: 'Automobile and Auto Components' },
  { symbol: 'HEXT.NS', name: "Hexaware Technologies Ltd.", sector: 'Information Technology' },
  { symbol: 'HSCL.NS', name: "Himadri Speciality Chemical Ltd.", sector: 'Chemicals' },
  { symbol: 'HINDALCO.NS', name: "Hindalco Industries Ltd.", sector: 'Metals & Mining' },
  { symbol: 'HAL.NS', name: "Hindustan Aeronautics Ltd.", sector: 'Capital Goods' },
  { symbol: 'HINDCOPPER.NS', name: "Hindustan Copper Ltd.", sector: 'Metals & Mining' },
  { symbol: 'HINDPETRO.NS', name: "Hindustan Petroleum Corporation Ltd.", sector: 'Oil Gas & Consumable Fuels' },
  { symbol: 'HINDUNILVR.NS', name: "Hindustan Unilever Ltd.", sector: 'Fast Moving Consumer Goods' },
  { symbol: 'HINDZINC.NS', name: "Hindustan Zinc Ltd.", sector: 'Metals & Mining' },
  { symbol: 'POWERINDIA.NS', name: "Hitachi Energy India Ltd.", sector: 'Capital Goods' },
  { symbol: 'HOMEFIRST.NS', name: "Home First Finance Company India Ltd.", sector: 'Financial Services' },
  { symbol: 'HONASA.NS', name: "Honasa Consumer Ltd.", sector: 'Fast Moving Consumer Goods' },
  { symbol: 'HONAUT.NS', name: "Honeywell Automation India Ltd.", sector: 'Capital Goods' },
  { symbol: 'HUDCO.NS', name: "Housing & Urban Development Corporation Ltd.", sector: 'Financial Services' },
  { symbol: 'HYUNDAI.NS', name: "Hyundai Motor India Ltd.", sector: 'Automobile and Auto Components' },
  { symbol: 'ICICIBANK.NS', name: "ICICI Bank Ltd.", sector: 'Financial Services' },
  { symbol: 'ICICIGI.NS', name: "ICICI Lombard General Insurance Company Ltd.", sector: 'Financial Services' },
  { symbol: 'ICICIPRULI.NS', name: "ICICI Prudential Life Insurance Company Ltd.", sector: 'Financial Services' },
  { symbol: 'IDBI.NS', name: "IDBI Bank Ltd.", sector: 'Financial Services' },
  { symbol: 'IDFCFIRSTB.NS', name: "IDFC First Bank Ltd.", sector: 'Financial Services' },
  { symbol: 'IFCI.NS', name: "IFCI Ltd.", sector: 'Financial Services' },
  { symbol: 'IIFL.NS', name: "IIFL Finance Ltd.", sector: 'Financial Services' },
  { symbol: 'INOXINDIA.NS', name: "INOX India Ltd.", sector: 'Capital Goods' },
  { symbol: 'IRB.NS', name: "IRB Infrastructure Developers Ltd.", sector: 'Construction' },
  { symbol: 'IRCON.NS', name: "IRCON International Ltd.", sector: 'Construction' },
  { symbol: 'ITCHOTELS.NS', name: "ITC Hotels Ltd.", sector: 'Consumer Services' },
  { symbol: 'ITC.NS', name: "ITC Ltd.", sector: 'Fast Moving Consumer Goods' },
  { symbol: 'ITI.NS', name: "ITI Ltd.", sector: 'Telecommunication' },
  { symbol: 'INDGN.NS', name: "Indegene Ltd.", sector: 'Healthcare' },
  { symbol: 'INDIACEM.NS', name: "India Cements Ltd.", sector: 'Construction Materials' },
  { symbol: 'INDIAMART.NS', name: "Indiamart Intermesh Ltd.", sector: 'Consumer Services' },
  { symbol: 'INDIANB.NS', name: "Indian Bank", sector: 'Financial Services' },
  { symbol: 'IEX.NS', name: "Indian Energy Exchange Ltd.", sector: 'Financial Services' },
  { symbol: 'INDHOTEL.NS', name: "Indian Hotels Co. Ltd.", sector: 'Consumer Services' },
  { symbol: 'IOC.NS', name: "Indian Oil Corporation Ltd.", sector: 'Oil Gas & Consumable Fuels' },
  { symbol: 'IOB.NS', name: "Indian Overseas Bank", sector: 'Financial Services' },
  { symbol: 'IRCTC.NS', name: "Indian Railway Catering And Tourism Corporation Ltd.", sector: 'Consumer Services' },
  { symbol: 'IRFC.NS', name: "Indian Railway Finance Corporation Ltd.", sector: 'Financial Services' },
  { symbol: 'IREDA.NS', name: "Indian Renewable Energy Development Agency Ltd.", sector: 'Financial Services' },
  { symbol: 'IGL.NS', name: "Indraprastha Gas Ltd.", sector: 'Oil Gas & Consumable Fuels' },
  { symbol: 'INDUSTOWER.NS', name: "Indus Towers Ltd.", sector: 'Telecommunication' },
  { symbol: 'INDUSINDBK.NS', name: "IndusInd Bank Ltd.", sector: 'Financial Services' },
  { symbol: 'NAUKRI.NS', name: "Info Edge (India) Ltd.", sector: 'Consumer Services' },
  { symbol: 'INFY.NS', name: "Infosys Ltd.", sector: 'Information Technology' },
  { symbol: 'INOXWIND.NS', name: "Inox Wind Ltd.", sector: 'Capital Goods' },
  { symbol: 'INTELLECT.NS', name: "Intellect Design Arena Ltd.", sector: 'Information Technology' },
  { symbol: 'INDIGO.NS', name: "InterGlobe Aviation Ltd.", sector: 'Services' },
  { symbol: 'IGIL.NS', name: "International Gemmological Institute (India) Ltd.", sector: 'Services' },
  { symbol: 'IKS.NS', name: "Inventurus Knowledge Solutions Ltd.", sector: 'Information Technology' },
  { symbol: 'IPCALAB.NS', name: "Ipca Laboratories Ltd.", sector: 'Healthcare' },
  { symbol: 'JBCHEPHARM.NS', name: "J.B. Chemicals & Pharmaceuticals Ltd.", sector: 'Healthcare' },
  { symbol: 'JKCEMENT.NS', name: "J.K. Cement Ltd.", sector: 'Construction Materials' },
  { symbol: 'JBMA.NS', name: "JBM Auto Ltd.", sector: 'Automobile and Auto Components' },
  { symbol: 'JKTYRE.NS', name: "JK Tyre & Industries Ltd.", sector: 'Automobile and Auto Components' },
  { symbol: 'JMFINANCIL.NS', name: "JM Financial Ltd.", sector: 'Financial Services' },
  { symbol: 'JSWENERGY.NS', name: "JSW Energy Ltd.", sector: 'Power' },
  { symbol: 'JSWINFRA.NS', name: "JSW Infrastructure Ltd.", sector: 'Services' },
  { symbol: 'JSWSTEEL.NS', name: "JSW Steel Ltd.", sector: 'Metals & Mining' },
  { symbol: 'JPPOWER.NS', name: "Jaiprakash Power Ventures Ltd.", sector: 'Power' },
  { symbol: 'J&KBANK.NS', name: "Jammu & Kashmir Bank Ltd.", sector: 'Financial Services' },
  { symbol: 'JINDALSAW.NS', name: "Jindal Saw Ltd.", sector: 'Capital Goods' },
  { symbol: 'JSL.NS', name: "Jindal Stainless Ltd.", sector: 'Metals & Mining' },
  { symbol: 'JINDALSTEL.NS', name: "Jindal Steel Ltd.", sector: 'Metals & Mining' },
  { symbol: 'JIOFIN.NS', name: "Jio Financial Services Ltd.", sector: 'Financial Services' },
  { symbol: 'JUBLFOOD.NS', name: "Jubilant Foodworks Ltd.", sector: 'Consumer Services' },
  { symbol: 'JUBLINGREA.NS', name: "Jubilant Ingrevia Ltd.", sector: 'Chemicals' },
  { symbol: 'JUBLPHARMA.NS', name: "Jubilant Pharmova Ltd.", sector: 'Healthcare' },
  { symbol: 'JWL.NS', name: "Jupiter Wagons Ltd.", sector: 'Capital Goods' },
  { symbol: 'JYOTHYLAB.NS', name: "Jyothy Labs Ltd.", sector: 'Fast Moving Consumer Goods' },
  { symbol: 'JYOTICNC.NS', name: "Jyoti CNC Automation Ltd.", sector: 'Capital Goods' },
  { symbol: 'KPRMILL.NS', name: "K.P.R. Mill Ltd.", sector: 'Textiles' },
  { symbol: 'KEI.NS', name: "KEI Industries Ltd.", sector: 'Capital Goods' },
  { symbol: 'KPITTECH.NS', name: "KPIT Technologies Ltd.", sector: 'Information Technology' },
  { symbol: 'KSB.NS', name: "KSB Ltd.", sector: 'Capital Goods' },
  { symbol: 'KAJARIACER.NS', name: "Kajaria Ceramics Ltd.", sector: 'Consumer Durables' },
  { symbol: 'KPIL.NS', name: "Kalpataru Projects International Ltd.", sector: 'Construction' },
  { symbol: 'KALYANKJIL.NS', name: "Kalyan Jewellers India Ltd.", sector: 'Consumer Durables' },
  { symbol: 'KARURVYSYA.NS', name: "Karur Vysya Bank Ltd.", sector: 'Financial Services' },
  { symbol: 'KAYNES.NS', name: "Kaynes Technology India Ltd.", sector: 'Capital Goods' },
  { symbol: 'KEC.NS', name: "Kec International Ltd.", sector: 'Construction' },
  { symbol: 'KFINTECH.NS', name: "Kfin Technologies Ltd.", sector: 'Financial Services' },
  { symbol: 'KIRLOSBROS.NS', name: "Kirloskar Brothers Ltd.", sector: 'Capital Goods' },
  { symbol: 'KIRLOSENG.NS', name: "Kirloskar Oil Eng Ltd.", sector: 'Capital Goods' },
  { symbol: 'KOTAKBANK.NS', name: "Kotak Mahindra Bank Ltd.", sector: 'Financial Services' },
  { symbol: 'KIMS.NS', name: "Krishna Institute of Medical Sciences Ltd.", sector: 'Healthcare' },
  { symbol: 'LTF.NS', name: "L&T Finance Ltd.", sector: 'Financial Services' },
  { symbol: 'LTTS.NS', name: "L&T Technology Services Ltd.", sector: 'Information Technology' },
  { symbol: 'LICHSGFIN.NS', name: "LIC Housing Finance Ltd.", sector: 'Financial Services' },
  { symbol: 'LTFOODS.NS', name: "LT Foods Ltd.", sector: 'Fast Moving Consumer Goods' },
  { symbol: 'LTIM.NS', name: "LTIMindtree Ltd.", sector: 'Information Technology' },
  { symbol: 'LT.NS', name: "Larsen & Toubro Ltd.", sector: 'Construction' },
  { symbol: 'LATENTVIEW.NS', name: "Latent View Analytics Ltd.", sector: 'Information Technology' },
  { symbol: 'LAURUSLABS.NS', name: "Laurus Labs Ltd.", sector: 'Healthcare' },
  { symbol: 'THELEELA.NS', name: "Leela Palaces Hotels & Resorts Ltd.", sector: 'Consumer Services' },
  { symbol: 'LEMONTREE.NS', name: "Lemon Tree Hotels Ltd.", sector: 'Consumer Services' },
  { symbol: 'LICI.NS', name: "Life Insurance Corporation of India", sector: 'Financial Services' },
  { symbol: 'LINDEINDIA.NS', name: "Linde India Ltd.", sector: 'Chemicals' },
  { symbol: 'LLOYDSME.NS', name: "Lloyds Metals And Energy Ltd.", sector: 'Metals & Mining' },
  { symbol: 'LODHA.NS', name: "Lodha Developers Ltd.", sector: 'Realty' },
  { symbol: 'LUPIN.NS', name: "Lupin Ltd.", sector: 'Healthcare' },
  { symbol: 'MMTC.NS', name: "MMTC Ltd.", sector: 'Services' },
  { symbol: 'MRF.NS', name: "MRF Ltd.", sector: 'Automobile and Auto Components' },
  { symbol: 'MGL.NS', name: "Mahanagar Gas Ltd.", sector: 'Oil Gas & Consumable Fuels' },
  { symbol: 'MAHSCOOTER.NS', name: "Maharashtra Scooters Ltd.", sector: 'Financial Services' },
  { symbol: 'MAHSEAMLES.NS', name: "Maharashtra Seamless Ltd.", sector: 'Capital Goods' },
  { symbol: 'M&MFIN.NS', name: "Mahindra & Mahindra Financial Services Ltd.", sector: 'Financial Services' },
  { symbol: 'M&M.NS', name: "Mahindra & Mahindra Ltd.", sector: 'Automobile and Auto Components' },
  { symbol: 'MANAPPURAM.NS', name: "Manappuram Finance Ltd.", sector: 'Financial Services' },
  { symbol: 'MRPL.NS', name: "Mangalore Refinery & Petrochemicals Ltd.", sector: 'Oil Gas & Consumable Fuels' },
  { symbol: 'MANKIND.NS', name: "Mankind Pharma Ltd.", sector: 'Healthcare' },
  { symbol: 'MARICO.NS', name: "Marico Ltd.", sector: 'Fast Moving Consumer Goods' },
  { symbol: 'MARUTI.NS', name: "Maruti Suzuki India Ltd.", sector: 'Automobile and Auto Components' },
  { symbol: 'MFSL.NS', name: "Max Financial Services Ltd.", sector: 'Financial Services' },
  { symbol: 'MAXHEALTH.NS', name: "Max Healthcare Institute Ltd.", sector: 'Healthcare' },
  { symbol: 'MAZDOCK.NS', name: "Mazagoan Dock Shipbuilders Ltd.", sector: 'Capital Goods' },
  { symbol: 'METROPOLIS.NS', name: "Metropolis Healthcare Ltd.", sector: 'Healthcare' },
  { symbol: 'MINDACORP.NS', name: "Minda Corporation Ltd.", sector: 'Automobile and Auto Components' },
  { symbol: 'MSUMI.NS', name: "Motherson Sumi Wiring India Ltd.", sector: 'Automobile and Auto Components' },
  { symbol: 'MOTILALOFS.NS', name: "Motilal Oswal Financial Services Ltd.", sector: 'Financial Services' },
  { symbol: 'MPHASIS.NS', name: "MphasiS Ltd.", sector: 'Information Technology' },
  { symbol: 'MCX.NS', name: "Multi Commodity Exchange of India Ltd.", sector: 'Financial Services' },
  { symbol: 'MUTHOOTFIN.NS', name: "Muthoot Finance Ltd.", sector: 'Financial Services' },
  { symbol: 'NATCOPHARM.NS', name: "NATCO Pharma Ltd.", sector: 'Healthcare' },
  { symbol: 'NBCC.NS', name: "NBCC (India) Ltd.", sector: 'Construction' },
  { symbol: 'NCC.NS', name: "NCC Ltd.", sector: 'Construction' },
  { symbol: 'NHPC.NS', name: "NHPC Ltd.", sector: 'Power' },
  { symbol: 'NLCINDIA.NS', name: "NLC India Ltd.", sector: 'Power' },
  { symbol: 'NMDC.NS', name: "NMDC Ltd.", sector: 'Metals & Mining' },
  { symbol: 'NSLNISP.NS', name: "NMDC Steel Ltd.", sector: 'Metals & Mining' },
  { symbol: 'NTPCGREEN.NS', name: "NTPC Green Energy Ltd.", sector: 'Power' },
  { symbol: 'NTPC.NS', name: "NTPC Ltd.", sector: 'Power' },
  { symbol: 'NH.NS', name: "Narayana Hrudayalaya Ltd.", sector: 'Healthcare' },
  { symbol: 'NATIONALUM.NS', name: "National Aluminium Co. Ltd.", sector: 'Metals & Mining' },
  { symbol: 'NAVA.NS', name: "Nava Ltd.", sector: 'Power' },
  { symbol: 'NAVINFLUOR.NS', name: "Navin Fluorine International Ltd.", sector: 'Chemicals' },
  { symbol: 'NESTLEIND.NS', name: "Nestle India Ltd.", sector: 'Fast Moving Consumer Goods' },
  { symbol: 'NETWEB.NS', name: "Netweb Technologies India Ltd.", sector: 'Information Technology' },
  { symbol: 'NEULANDLAB.NS', name: "Neuland Laboratories Ltd.", sector: 'Healthcare' },
  { symbol: 'NEWGEN.NS', name: "Newgen Software Technologies Ltd.", sector: 'Information Technology' },
  { symbol: 'NAM-INDIA.NS', name: "Nippon Life India Asset Management Ltd.", sector: 'Financial Services' },
  { symbol: 'NIVABUPA.NS', name: "Niva Bupa Health Insurance Company Ltd.", sector: 'Financial Services' },
  { symbol: 'NUVAMA.NS', name: "Nuvama Wealth Management Ltd.", sector: 'Financial Services' },
  { symbol: 'NUVOCO.NS', name: "Nuvoco Vistas Corporation Ltd.", sector: 'Construction Materials' },
  { symbol: 'OBEROIRLTY.NS', name: "Oberoi Realty Ltd.", sector: 'Realty' },
  { symbol: 'ONGC.NS', name: "Oil & Natural Gas Corporation Ltd.", sector: 'Oil Gas & Consumable Fuels' },
  { symbol: 'OIL.NS', name: "Oil India Ltd.", sector: 'Oil Gas & Consumable Fuels' },
  { symbol: 'OLAELEC.NS', name: "Ola Electric Mobility Ltd.", sector: 'Automobile and Auto Components' },
  { symbol: 'OLECTRA.NS', name: "Olectra Greentech Ltd.", sector: 'Automobile and Auto Components' },
  { symbol: 'PAYTM.NS', name: "One 97 Communications Ltd.", sector: 'Financial Services' },
  { symbol: 'ONESOURCE.NS', name: "Onesource Specialty Pharma Ltd.", sector: 'Healthcare' },
  { symbol: 'OFSS.NS', name: "Oracle Financial Services Software Ltd.", sector: 'Information Technology' },
  { symbol: 'POLICYBZR.NS', name: "PB Fintech Ltd.", sector: 'Financial Services' },
  { symbol: 'PCBL.NS', name: "PCBL Chemical Ltd.", sector: 'Chemicals' },
  { symbol: 'PGEL.NS', name: "PG Electroplast Ltd.", sector: 'Consumer Durables' },
  { symbol: 'PIIND.NS', name: "PI Industries Ltd.", sector: 'Chemicals' },
  { symbol: 'PNBHOUSING.NS', name: "PNB Housing Finance Ltd.", sector: 'Financial Services' },
  { symbol: 'PTCIL.NS', name: "PTC Industries Ltd.", sector: 'Capital Goods' },
  { symbol: 'PVRINOX.NS', name: "PVR INOX Ltd.", sector: 'Media Entertainment & Publication' },
  { symbol: 'PAGEIND.NS', name: "Page Industries Ltd.", sector: 'Textiles' },
  { symbol: 'PATANJALI.NS', name: "Patanjali Foods Ltd.", sector: 'Fast Moving Consumer Goods' },
  { symbol: 'PERSISTENT.NS', name: "Persistent Systems Ltd.", sector: 'Information Technology' },
  { symbol: 'PETRONET.NS', name: "Petronet LNG Ltd.", sector: 'Oil Gas & Consumable Fuels' },
  { symbol: 'PFIZER.NS', name: "Pfizer Ltd.", sector: 'Healthcare' },
  { symbol: 'PHOENIXLTD.NS', name: "Phoenix Mills Ltd.", sector: 'Realty' },
  { symbol: 'PIDILITIND.NS', name: "Pidilite Industries Ltd.", sector: 'Chemicals' },
  { symbol: 'PPLPHARMA.NS', name: "Piramal Pharma Ltd.", sector: 'Healthcare' },
  { symbol: 'POLYMED.NS', name: "Poly Medicure Ltd.", sector: 'Healthcare' },
  { symbol: 'POLYCAB.NS', name: "Polycab India Ltd.", sector: 'Capital Goods' },
  { symbol: 'POONAWALLA.NS', name: "Poonawalla Fincorp Ltd.", sector: 'Financial Services' },
  { symbol: 'PFC.NS', name: "Power Finance Corporation Ltd.", sector: 'Financial Services' },
  { symbol: 'POWERGRID.NS', name: "Power Grid Corporation of India Ltd.", sector: 'Power' },
  { symbol: 'PRAJIND.NS', name: "Praj Industries Ltd.", sector: 'Capital Goods' },
  { symbol: 'PREMIERENE.NS', name: "Premier Energies Ltd.", sector: 'Capital Goods' },
  { symbol: 'PRESTIGE.NS', name: "Prestige Estates Projects Ltd.", sector: 'Realty' },
  { symbol: 'PGHH.NS', name: "Procter & Gamble Hygiene & Health Care Ltd.", sector: 'Fast Moving Consumer Goods' },
  { symbol: 'PNB.NS', name: "Punjab National Bank", sector: 'Financial Services' },
  { symbol: 'RRKABEL.NS', name: "R R Kabel Ltd.", sector: 'Capital Goods' },
  { symbol: 'RBLBANK.NS', name: "RBL Bank Ltd.", sector: 'Financial Services' },
  { symbol: 'RECLTD.NS', name: "REC Ltd.", sector: 'Financial Services' },
  { symbol: 'RHIM.NS', name: "RHI MAGNESITA INDIA LTD.", sector: 'Capital Goods' },
  { symbol: 'RITES.NS', name: "RITES Ltd.", sector: 'Construction' },
  { symbol: 'RADICO.NS', name: "Radico Khaitan Ltd", sector: 'Fast Moving Consumer Goods' },
  { symbol: 'RVNL.NS', name: "Rail Vikas Nigam Ltd.", sector: 'Construction' },
  { symbol: 'RAILTEL.NS', name: "Railtel Corporation Of India Ltd.", sector: 'Telecommunication' },
  { symbol: 'RAINBOW.NS', name: "Rainbow Childrens Medicare Ltd.", sector: 'Healthcare' },
  { symbol: 'RKFORGE.NS', name: "Ramkrishna Forgings Ltd.", sector: 'Automobile and Auto Components' },
  { symbol: 'RCF.NS', name: "Rashtriya Chemicals & Fertilizers Ltd.", sector: 'Chemicals' },
  { symbol: 'REDINGTON.NS', name: "Redington Ltd.", sector: 'Services' },
  { symbol: 'RELIANCE.NS', name: "Reliance Industries Ltd.", sector: 'Oil Gas & Consumable Fuels' },
  { symbol: 'RELINFRA.NS', name: "Reliance Infrastructure Ltd.", sector: 'Power' },
  { symbol: 'RPOWER.NS', name: "Reliance Power Ltd.", sector: 'Power' },
  { symbol: 'SBFC.NS', name: "SBFC Finance Ltd.", sector: 'Financial Services' },
  { symbol: 'SBICARD.NS', name: "SBI Cards and Payment Services Ltd.", sector: 'Financial Services' },
  { symbol: 'SBILIFE.NS', name: "SBI Life Insurance Company Ltd.", sector: 'Financial Services' },
  { symbol: 'SJVN.NS', name: "SJVN Ltd.", sector: 'Power' },
  { symbol: 'SKFINDIA.NS', name: "SKF India Ltd.", sector: 'Automobile and Auto Components' },
  { symbol: 'SRF.NS', name: "SRF Ltd.", sector: 'Chemicals' },
  { symbol: 'SAGILITY.NS', name: "Sagility Ltd.", sector: 'Information Technology' },
  { symbol: 'SAILIFE.NS', name: "Sai Life Sciences Ltd.", sector: 'Healthcare' },
  { symbol: 'SAMMAANCAP.NS', name: "Sammaan Capital Ltd.", sector: 'Financial Services' },
  { symbol: 'MOTHERSON.NS', name: "Samvardhana Motherson International Ltd.", sector: 'Automobile and Auto Components' },
  { symbol: 'SAPPHIRE.NS', name: "Sapphire Foods India Ltd.", sector: 'Consumer Services' },
  { symbol: 'SARDAEN.NS', name: "Sarda Energy and Minerals Ltd.", sector: 'Metals & Mining' },
  { symbol: 'SAREGAMA.NS', name: "Saregama India Ltd", sector: 'Media Entertainment & Publication' },
  { symbol: 'SCHAEFFLER.NS', name: "Schaeffler India Ltd.", sector: 'Automobile and Auto Components' },
  { symbol: 'SCHNEIDER.NS', name: "Schneider Electric Infrastructure Ltd.", sector: 'Capital Goods' },
  { symbol: 'SCI.NS', name: "Shipping Corporation of India Ltd.", sector: 'Services' },
  { symbol: 'SHREECEM.NS', name: "Shree Cement Ltd.", sector: 'Construction Materials' },
  { symbol: 'SHRIRAMFIN.NS', name: "Shriram Finance Ltd.", sector: 'Financial Services' },
  { symbol: 'SHYAMMETL.NS', name: "Shyam Metalics and Energy Ltd.", sector: 'Capital Goods' },
  { symbol: 'ENRIN.NS', name: "Siemens Energy India Ltd.", sector: 'Capital Goods' },
  { symbol: 'SIEMENS.NS', name: "Siemens Ltd.", sector: 'Capital Goods' },
  { symbol: 'SIGNATURE.NS', name: "Signatureglobal (India) Ltd.", sector: 'Realty' },
  { symbol: 'SOBHA.NS', name: "Sobha Ltd.", sector: 'Realty' },
  { symbol: 'SOLARINDS.NS', name: "Solar Industries India Ltd.", sector: 'Chemicals' },
  { symbol: 'SONACOMS.NS', name: "Sona BLW Precision Forgings Ltd.", sector: 'Automobile and Auto Components' },
  { symbol: 'SONATSOFTW.NS', name: "Sonata Software Ltd.", sector: 'Information Technology' },
  { symbol: 'STARHEALTH.NS', name: "Star Health and Allied Insurance Company Ltd.", sector: 'Financial Services' },
  { symbol: 'SBIN.NS', name: "State Bank of India", sector: 'Financial Services' },
  { symbol: 'SAIL.NS', name: "Steel Authority of India Ltd.", sector: 'Metals & Mining' },
  { symbol: 'SUMICHEM.NS', name: "Sumitomo Chemical India Ltd.", sector: 'Chemicals' },
  { symbol: 'SUNPHARMA.NS', name: "Sun Pharmaceutical Industries Ltd.", sector: 'Healthcare' },
  { symbol: 'SUNTV.NS', name: "Sun TV Network Ltd.", sector: 'Media Entertainment & Publication' },
  { symbol: 'SUNDARMFIN.NS', name: "Sundaram Finance Ltd.", sector: 'Financial Services' },
  { symbol: 'SUNDRMFAST.NS', name: "Sundram Fasteners Ltd.", sector: 'Automobile and Auto Components' },
  { symbol: 'SUPREMEIND.NS', name: "Supreme Industries Ltd.", sector: 'Capital Goods' },
  { symbol: 'SUZLON.NS', name: "Suzlon Energy Ltd.", sector: 'Capital Goods' },
  { symbol: 'SWANCORP.NS', name: "Swan Corp Ltd.", sector: 'Chemicals' },
  { symbol: 'SWIGGY.NS', name: "Swiggy Ltd.", sector: 'Consumer Services' },
  { symbol: 'SYNGENE.NS', name: "Syngene International Ltd.", sector: 'Healthcare' },
  { symbol: 'SYRMA.NS', name: "Syrma SGS Technology Ltd.", sector: 'Capital Goods' },
  { symbol: 'TBOTEK.NS', name: "TBO Tek Ltd.", sector: 'Consumer Services' },
  { symbol: 'TVSMOTOR.NS', name: "TVS Motor Company Ltd.", sector: 'Automobile and Auto Components' },
  { symbol: 'TATACHEM.NS', name: "Tata Chemicals Ltd.", sector: 'Chemicals' },
  { symbol: 'TATACOMM.NS', name: "Tata Communications Ltd.", sector: 'Telecommunication' },
  { symbol: 'TCS.NS', name: "Tata Consultancy Services Ltd.", sector: 'Information Technology' },
  { symbol: 'TATACONSUM.NS', name: "Tata Consumer Products Ltd.", sector: 'Fast Moving Consumer Goods' },
  { symbol: 'TATAELXSI.NS', name: "Tata Elxsi Ltd.", sector: 'Information Technology' },
  { symbol: 'TATAINVEST.NS', name: "Tata Investment Corporation Ltd.", sector: 'Financial Services' },
  { symbol: 'TMPV.NS', name: "Tata Motors Passenger Vehicles Ltd.", sector: 'Automobile and Auto Components' },
  { symbol: 'TATAPOWER.NS', name: "Tata Power Co. Ltd.", sector: 'Power' },
  { symbol: 'TATASTEEL.NS', name: "Tata Steel Ltd.", sector: 'Metals & Mining' },
  { symbol: 'TATATECH.NS', name: "Tata Technologies Ltd.", sector: 'Information Technology' },
  { symbol: 'TTML.NS', name: "Tata Teleservices (Maharashtra) Ltd.", sector: 'Telecommunication' },
  { symbol: 'TECHM.NS', name: "Tech Mahindra Ltd.", sector: 'Information Technology' },
  { symbol: 'TECHNOE.NS', name: "Techno Electric & Engineering Company Ltd.", sector: 'Construction' },
  { symbol: 'TEJASNET.NS', name: "Tejas Networks Ltd.", sector: 'Telecommunication' },
  { symbol: 'NIACL.NS', name: "The New India Assurance Company Ltd.", sector: 'Financial Services' },
  { symbol: 'RAMCOCEM.NS', name: "The Ramco Cements Ltd.", sector: 'Construction Materials' },
  { symbol: 'THERMAX.NS', name: "Thermax Ltd.", sector: 'Capital Goods' },
  { symbol: 'TIMKEN.NS', name: "Timken India Ltd.", sector: 'Capital Goods' },
  { symbol: 'TITAGARH.NS', name: "Titagarh Rail Systems Ltd.", sector: 'Capital Goods' },
  { symbol: 'TITAN.NS', name: "Titan Company Ltd.", sector: 'Consumer Durables' },
  { symbol: 'TORNTPHARM.NS', name: "Torrent Pharmaceuticals Ltd.", sector: 'Healthcare' },
  { symbol: 'TORNTPOWER.NS', name: "Torrent Power Ltd.", sector: 'Power' },
  { symbol: 'TARIL.NS', name: "Transformers And Rectifiers (India) Ltd.", sector: 'Capital Goods' },
  { symbol: 'TRENT.NS', name: "Trent Ltd.", sector: 'Consumer Services' },
  { symbol: 'TRIDENT.NS', name: "Trident Ltd.", sector: 'Textiles' },
  { symbol: 'TRIVENI.NS', name: "Triveni Engineering & Industries Ltd.", sector: 'Fast Moving Consumer Goods' },
  { symbol: 'TRITURBINE.NS', name: "Triveni Turbine Ltd.", sector: 'Capital Goods' },
  { symbol: 'TIINDIA.NS', name: "Tube Investments of India Ltd.", sector: 'Automobile and Auto Components' },
  { symbol: 'UCOBANK.NS', name: "UCO Bank", sector: 'Financial Services' },
  { symbol: 'UNOMINDA.NS', name: "UNO Minda Ltd.", sector: 'Automobile and Auto Components' },
  { symbol: 'UPL.NS', name: "UPL Ltd.", sector: 'Chemicals' },
  { symbol: 'UTIAMC.NS', name: "UTI Asset Management Company Ltd.", sector: 'Financial Services' },
  { symbol: 'ULTRACEMCO.NS', name: "UltraTech Cement Ltd.", sector: 'Construction Materials' },
  { symbol: 'UNIONBANK.NS', name: "Union Bank of India", sector: 'Financial Services' },
  { symbol: 'UBL.NS', name: "United Breweries Ltd.", sector: 'Fast Moving Consumer Goods' },
  { symbol: 'UNITDSPR.NS', name: "United Spirits Ltd.", sector: 'Fast Moving Consumer Goods' },
  { symbol: 'USHAMART.NS', name: "Usha Martin Ltd.", sector: 'Capital Goods' },
  { symbol: 'VGUARD.NS', name: "V-Guard Industries Ltd.", sector: 'Consumer Durables' },
  { symbol: 'DBREALTY.NS', name: "Valor Estate Ltd.", sector: 'Consumer Services' },
  { symbol: 'VTL.NS', name: "Vardhman Textiles Ltd.", sector: 'Textiles' },
  { symbol: 'VBL.NS', name: "Varun Beverages Ltd.", sector: 'Fast Moving Consumer Goods' },
  { symbol: 'MANYAVAR.NS', name: "Vedant Fashions Ltd.", sector: 'Consumer Services' },
  { symbol: 'VEDL.NS', name: "Vedanta Ltd.", sector: 'Metals & Mining' },
  { symbol: 'VENTIVE.NS', name: "Ventive Hospitality Ltd.", sector: 'Consumer Services' },
  { symbol: 'VIJAYA.NS', name: "Vijaya Diagnostic Centre Ltd.", sector: 'Healthcare' },
  { symbol: 'VMM.NS', name: "Vishal Mega Mart Ltd.", sector: 'Consumer Services' },
  { symbol: 'IDEA.NS', name: "Vodafone Idea Ltd.", sector: 'Telecommunication' },
  { symbol: 'VOLTAS.NS', name: "Voltas Ltd.", sector: 'Consumer Durables' },
  { symbol: 'WAAREEENER.NS', name: "Waaree Energies Ltd.", sector: 'Capital Goods' },
  { symbol: 'WELCORP.NS', name: "Welspun Corp Ltd.", sector: 'Capital Goods' },
  { symbol: 'WELSPUNLIV.NS', name: "Welspun Living Ltd.", sector: 'Textiles' },
  { symbol: 'WHIRLPOOL.NS', name: "Whirlpool of India Ltd.", sector: 'Consumer Durables' },
  { symbol: 'WIPRO.NS', name: "Wipro Ltd.", sector: 'Information Technology' },
  { symbol: 'WOCKPHARMA.NS', name: "Wockhardt Ltd.", sector: 'Healthcare' },
  { symbol: 'YESBANK.NS', name: "Yes Bank Ltd.", sector: 'Financial Services' },
  { symbol: 'ZFCVINDIA.NS', name: "ZF Commercial Vehicle Control Systems India Ltd.", sector: 'Automobile and Auto Components' },
  { symbol: 'ZEEL.NS', name: "Zee Entertainment Enterprises Ltd.", sector: 'Media Entertainment & Publication' },
  { symbol: 'ZENTEC.NS', name: "Zen Technologies Ltd.", sector: 'Capital Goods' },
  { symbol: 'ZENSARTECH.NS', name: "Zensar Technolgies Ltd.", sector: 'Information Technology' },
  { symbol: 'ZYDUSLIFE.NS', name: "Zydus Lifesciences Ltd.", sector: 'Healthcare' },
  { symbol: 'ECLERX.NS', name: "eClerx Services Ltd.", sector: 'Services' },
];